services:
  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - '3000:3000'
    volumes:
      - ./backend:/app
    command: npm run dev
    environment:
      - NODE_ENV=development
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - '8080:80'
    volumes:
      - ./frontend:/usr/share/nginx/html
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
